// ==============================================================================
// کاتالوگ بنچمارک استاندارد بازار نوشت‌افزار ایران (Stationery Market Benchmark Catalog)
// این کاتالوگ صرفاً داده‌های مرجع، بنچمارک قیمت و متادیتای پایه صنف تحریر است.
// برای استعلام‌های زنده وب، توابع marketAggregator مستقیماً به API متصل می‌شوند.
// ==============================================================================

import { TorobProductInfo } from '../../src/types';
import { STATIONERY_IMAGE_BANK } from './imageResolver';

export const stationeryMarketBenchmarkCatalog: TorobProductInfo[] = [
  {
    torobCode: 'TRB-PAP-A4-DBLA',
    title: 'کاغذ A4 دابل ای (Double A) بسته ۵۰۰ عددی ۸۰ گرمی',
    category: 'کاغذ و مقوا',
    subCategory: 'کاغذ A4',
    brand: 'Double A',
    unit: 'بسته',
    image: STATIONERY_IMAGE_BANK.paperDoubleA,
    gallery: [
      STATIONERY_IMAGE_BANK.paperDoubleA,
      STATIONERY_IMAGE_BANK.paperCopyMax,
    ],
    torobUrl: 'https://torob.com/search/?query=%DA%A9%D8%A7%D8%BA%D8%B0+A4+%D8%AF%D8%A7%D8%A8%D9%84+%D8%A7%DB%8C',
    specs: {
      'گرماژ': '۸۰ گرم واقعی',
      'سایز': 'A4 (210x297 mm)',
      'تعداد در بسته': '۵۰۰ برگ',
      'تعداد در کارتن': '۵ بسته (۲۵۰۰ برگ)',
      'کشور سازنده': 'تایلند (اورجینال)',
    },
    description: 'کاغذ با کیفیت بسیار بالا، سفیدی ۹۸٪ و تراکم عالی بدون گیر کردن در پرینترهای لیزری و دستگاه‌های فتوکپی.',
    sellers: [
      {
        storeName: 'دیجی‌کالا (فروشنده برگزیده)',
        city: 'تهران',
        score: 4.8,
        price: 265000,
        inStock: true,
        lastUpdated: 'پایگاه داده مرجع',
        updatedRecently: false,
        warranty: 'ضمانت اصالت و سلامت فیزیکی',
        shopUrl: 'https://www.digikala.com/search/?q=%DA%A9%D8%A7%D8%BA%D8%B0%20A4%20%D8%AF%D8%A7%D8%A8%D9%84%20%D8%A7%DB%8C',
      },
      {
        storeName: 'تحریر بازار (ترب)',
        city: 'اصفهان',
        score: 4.7,
        price: 249000,
        inStock: true,
        lastUpdated: 'پایگاه داده مرجع',
        updatedRecently: false,
        warranty: 'ارسال فوری سراسر کشور',
        shopUrl: 'https://torob.com/search/?query=%DA%A9%D8%A7%D8%BA%D8%B0+A4+%D8%AF%D8%A7%D8%A8%D9%84+%D8%A7%DB%8C',
      },
      {
        storeName: 'کاغذیران (تایم تحریر)',
        city: 'مشهد',
        score: 4.6,
        price: 252000,
        inStock: true,
        lastUpdated: 'پایگاه داده مرجع',
        updatedRecently: false,
        warranty: 'تضمین بازگشت وجه ۷ روزه',
        shopUrl: 'https://timetahrire.com',
      },
    ],
    minPrice: 248000,
    maxPrice: 285000,
    avgPrice: 262000,
    suggestedBuyPrice: 215000,
    suggestedSalePrice: 247000,
    suggestedShop1Price: 275000,
    suggestedShop2Price: 247000,
    suggestedShop3Price: 232000,
    activeSellersCount: 42,
    totalSellersCount: 78,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: {
      marginStrategy: 'سود ۱۵٪ آنلاین جهت تصاحب رتبه ۱ ترب؛ سود ۲۸٪ در فروش حضوری',
      competitiveEdge: 'عرضه با کارتن اورجینال شرکتی و ارسال ضدضربه',
      targetAudience: 'ادارات، دانشگاه‌ها، دفاتر اسناد رسمی و مراکز کپی',
      inventoryAdvice: 'تامین ۵۰ کارتن ۵ بسته‌ای قبل از پیک آغاز سال تحصیلی',
    },
  },
  {
    torobCode: 'TRB-PAP-A4-CPMX',
    title: 'کاغذ A4 کپی مکس (Copymax) بسته ۵۰۰ عددی ۸۰ گرمی',
    category: 'کاغذ و مقوا',
    subCategory: 'کاغذ A4',
    brand: 'Copymax',
    unit: 'بسته',
    image: STATIONERY_IMAGE_BANK.paperCopyMax,
    torobUrl: 'https://torob.com/search/?query=%DA%A9%D8%A7%D8%BA%D8%B0+A4+%DA%A9%D9%BE%DB%8C+%D9%85%DA%A9%D8%B3',
    specs: {
      'گرماژ': '۸۰ گرم',
      'برش': 'لیزری بدون پرز',
      'تعداد در بسته': '۵۰۰ برگ',
      'کاربرد': 'پرینت دورو، کپی و فکس',
    },
    description: 'پرمصرف‌ترین و اقتصادی‌ترین کاغذ تحریر بازار ایران مناسب مصرف روزمره مدارس و شرکت‌ها.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.6, price: 185000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'اصالت کالا', shopUrl: 'https://www.digikala.com' },
      { storeName: 'ارزان تحریر ترب', city: 'تهران', score: 4.8, price: 172000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'تحویل اکسپرس', shopUrl: 'https://torob.com' },
    ],
    minPrice: 172000,
    maxPrice: 198000,
    avgPrice: 184000,
    suggestedBuyPrice: 148000,
    suggestedSalePrice: 171000,
    suggestedShop1Price: 195000,
    suggestedShop2Price: 171000,
    suggestedShop3Price: 159000,
    activeSellersCount: 65,
    totalSellersCount: 110,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۱۵٪ آنلاین، سود ۳۱٪ حضوری', competitiveEdge: 'پک اقتصادی ۵ بسته‌ای با تخفیف ۳ درصدی', targetAudience: 'مدارس، شرکت‌ها و مصرف خانگی', inventoryAdvice: 'گردش فوق‌العاده سریع' },
  },
  {
    torobCode: 'TRB-PEN-PAN-SP105',
    title: 'خودکار پنتر مدل SP-105 بسته ۸ عددی رنگی نوک ۱.۰ میلی‌متر',
    category: 'نوشت‌افزار و تحریر',
    subCategory: 'خودکار و روان‌نویس',
    brand: 'Panter',
    unit: 'بسته',
    image: STATIONERY_IMAGE_BANK.penPanterSp105,
    torobUrl: 'https://torob.com/search/?query=%D8%AE%D9%88%D8%AF%DA%A9%D8%A7%D8%B1+%D9%BE%D9%86%D8%AA%D8%B1+sp105',
    specs: {
      'ضخامت نوک': '۱.۰ میلی‌متر روان (Semi-Gel)',
      'تعداد رنگ': '۸ رنگ کاربردی و فانتزی',
      'گریپ': 'لاستیکی ارگونومیک ضدخستگی',
      'جوهر': 'روان بدون پس‌دادن یا جوهرریزی',
    },
    description: 'محبوب‌ترین ست خودکار رنگی دانش‌آموزی و دانشجویی با ارگونومی عالی دست و نگارش یکنواخت.',
    sellers: [
      { storeName: 'دیجی‌کالا (دیجی‌کالا سرویس)', city: 'تهران', score: 4.8, price: 115000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ضمانت بازگشت کالا', shopUrl: 'https://www.digikala.com' },
      { storeName: 'تحریر پارس (ترب)', city: 'قم', score: 4.9, price: 99000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال با پست پیشتاز', shopUrl: 'https://torob.com' },
      { storeName: 'تایم تحریر', city: 'مشهد', score: 4.7, price: 104000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ضمانت سلامت فیزیکی', shopUrl: 'https://timetahrire.com' },
    ],
    minPrice: 99000,
    maxPrice: 125000,
    avgPrice: 112000,
    suggestedBuyPrice: 78000,
    suggestedSalePrice: 98000,
    suggestedShop1Price: 120000,
    suggestedShop2Price: 98000,
    suggestedShop3Price: 87000,
    activeSellersCount: 38,
    totalSellersCount: 60,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۵٪ آنلاین، سود ۵۳٪ حضوری', competitiveEdge: 'ارسال با دفتر یادداشت طرح‌دار هدیه خطی‌نو', targetAudience: 'دانش‌آموزان، کنکوری‌ها و دانشجویان', inventoryAdvice: 'تامین مستمر حداقل ۴۰ بسته' },
  },
  {
    torobCode: 'TRB-PEN-KIAN-BOX50',
    title: 'خودکار کیان نوک ۰.۷ یا ۱.۰ میلی‌متر بسته ۵۰ عددی',
    category: 'نوشت‌افزار و تحریر',
    subCategory: 'خودکار و روان‌نویس',
    brand: 'Kian',
    unit: 'جعبه',
    image: STATIONERY_IMAGE_BANK.penKianBox,
    torobUrl: 'https://torob.com/search/?query=%D8%AE%D9%88%D8%AF%DA%A9%D8%A7%D8%B1+%DA%A9%DB%8C%D8%A7%D9%86+%D8%A8%D8%B3%D8%AA%D9%87+50+%D8%B9%D8%AF%D8%AF%DB%8C',
    specs: { 'تعداد در جعبه': '۵۰ عدد', 'ضخامت ساچمه': '۰.۷ میلی‌متر OBG', 'رنگ‌بندی': 'آبی / مشکی / قرمز / سبز', 'ساخت': 'ایران با فناوری جوهر آلمان' },
    description: 'پرفروش‌ترین خودکار اداری و مدرسه‌ای ایران با ماندگاری بالا، بدون قطعی و جوهر روان.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.8, price: 340000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'اصالت کالا', shopUrl: 'https://www.digikala.com' },
      { storeName: 'تحریران ترب', city: 'تهران', score: 4.9, price: 310000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال فوری', shopUrl: 'https://torob.com' },
    ],
    minPrice: 310000,
    maxPrice: 375000,
    avgPrice: 338000,
    suggestedBuyPrice: 265000,
    suggestedSalePrice: 308000,
    suggestedShop1Price: 360000,
    suggestedShop2Price: 308000,
    suggestedShop3Price: 285000,
    activeSellersCount: 54,
    totalSellersCount: 92,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۱۶٪ آنلاین، سود ۳۵٪ فروش تکی یا جعبه‌ای حضوری', competitiveEdge: 'امکان انتخاب تک‌رنگ یا میکس', targetAudience: 'بانک‌ها، شرکت‌ها، موسسات آموزشی', inventoryAdvice: 'تامین ۲۰ کارتن (شامل ۴۰ جعبه)' },
  },
  {
    torobCode: 'TRB-NB-SPIRAL-80',
    title: 'دفتر مشق ۸۰ برگ سیمی جلد سخت خطی‌نو طرح کلاسیک',
    category: 'دفتر و نوشت‌افزار',
    subCategory: 'دفتر سیمی',
    brand: 'خطی‌نو (Khatinoo)',
    unit: 'جلد',
    image: STATIONERY_IMAGE_BANK.notebookSpiralKhatinoo,
    torobUrl: 'https://torob.com/search/?query=%D8%AF%D9%81%D8%AA%D8%B1+80+%D8%A8%D8%B1%DA%AF+%D8%B3%DB%8C%D9%85%DB%8C',
    specs: { 'تعداد برگ': '۸۰ برگ خط‌دار', 'نوع صحافی': 'سیمی دوبل فلزی ضدزنگ', 'جنس جلد': 'گلاسه ضخیم ۳۰۰ گرم با روکش سلفون مات', 'کاغذ داخلی': '۷۰ گرم سفید اندونزی' },
    description: 'دفتر مشق استاندارد با خط‌کشی مهندسی‌شده، جلد مقاوم و برگه‌خوری روان بدون پاره‌شدن.',
    sellers: [
      { storeName: 'فروشگاه مرکزی خطی‌نو', city: 'تهران', score: 5.0, price: 68000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'تولید اختصاصی و تضمین کیفیت', shopUrl: '#' },
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.7, price: 82000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'اصالت کالا', shopUrl: 'https://www.digikala.com' },
      { storeName: 'فروشگاه‌های همکار ترب', city: 'اصفهان', score: 4.8, price: 74000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال سراسری', shopUrl: 'https://torob.com' },
    ],
    minPrice: 68000,
    maxPrice: 89000,
    avgPrice: 77000,
    suggestedBuyPrice: 42000,
    suggestedSalePrice: 68000,
    suggestedShop1Price: 85000,
    suggestedShop2Price: 68000,
    suggestedShop3Price: 52000,
    activeSellersCount: 26,
    totalSellersCount: 45,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۶۲٪ مستقیم تولید داخل', competitiveEdge: 'برند اختصاصی خطی‌نو، کیفیت کاغذ بالاتر نسبت به رقبا', targetAudience: 'دانش‌آموزان ابتدایی تا دبیرستان', inventoryAdvice: 'تولید انبوه قبل از شهریور' },
  },
  {
    torobCode: 'TRB-NB-PAPCO-100',
    title: 'کلاسور ۲۰۰ برگ ۲۶ حلقه پاپکو (Papco) مدل NB-654',
    category: 'دفتر و نوشت‌افزار',
    subCategory: 'کلاسور و زونکن',
    brand: 'Papco',
    unit: 'جلد',
    image: STATIONERY_IMAGE_BANK.notebookPapco,
    torobUrl: 'https://torob.com/search/?query=%DA%A9%D9%84%D8%A7%D8%B3%D9%88%D8%B1+%D9%BE%D8%A7%D9%BE%DA%A9%D9%88',
    specs: { 'تعداد حلقه': '۲۶ حلقه پلاستیکی مرغوب', 'ظرفیت': 'تا ۲۰۰ برگ کاغذ کلاسوری', 'اقلام همراه': '۴ دیوایدر رنگی + ۱۰۰ برگ کاغذ خط‌دار پاپکو', 'جنس جلد': 'پلی‌پروپیلن مات ضدآب' },
    description: 'کلاسور استاندارد دانشگاهی پاپکو با قفل روان و دیوایدرهای تفکیک دروس.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.9, price: 235000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'گارانتی اصالت پاپکو', shopUrl: 'https://www.digikala.com' },
      { storeName: 'پاپکو سنتر (ترب)', city: 'تهران', score: 4.9, price: 215000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'نمایندگی رسمی', shopUrl: 'https://torob.com' },
    ],
    minPrice: 215000,
    maxPrice: 255000,
    avgPrice: 232000,
    suggestedBuyPrice: 175000,
    suggestedSalePrice: 212000,
    suggestedShop1Price: 245000,
    suggestedShop2Price: 212000,
    suggestedShop3Price: 192000,
    activeSellersCount: 30,
    totalSellersCount: 52,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۱٪ آنلاین، سود ۴۰٪ حضوری', competitiveEdge: 'فروش همراه با بسته یدک کاغذ ۱۰۰ برگ پاپکو', targetAudience: 'دانشجویان و دانش‌آموزان مقطع متوسطه', inventoryAdvice: 'تامین رنگ‌بندی‌های پرطرفدار (مشکی، سرمه‌ای، دودی)' },
  },
  {
    torobCode: 'TRB-PEN-ZEBRA-SARASA',
    title: 'روان‌نویس زبرا مدل ساراسا کلیپ ۰.۵ میلی‌متر (Zebra Sarasa Clip)',
    category: 'نوشت‌افزار و تحریر',
    subCategory: 'خودکار و روان‌نویس',
    brand: 'Zebra',
    unit: 'عدد',
    image: STATIONERY_IMAGE_BANK.penZebraSarasa,
    torobUrl: 'https://torob.com/search/?query=%D8%B2%D8%A8%D8%B1%D8%A7+%D8%B3%D8%A7%D8%B1%D8%A7%D8%B3%D8%A7',
    specs: { 'نوع جوهر': 'ژله‌ای بر پایه آب (Water-based Gel)', 'کشور سازنده': 'ژاپن (اصل)', 'ضخامت نوک': '۰.۵ میلی‌متر فوق دقیق', 'کلیپ': 'فنری متحرک محکم' },
    description: 'روان‌نویس حرفه‌ای ژاپنی با جوهر بسیار روان، ضدآب و بدون پخش‌شدگی روی کاغذ.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.9, price: 92000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ضمانت اصالت ژاپن', shopUrl: 'https://www.digikala.com' },
      { storeName: 'شهر قلم (ترب)', city: 'شیراز', score: 4.8, price: 79000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال فوری', shopUrl: 'https://torob.com' },
    ],
    minPrice: 79000,
    maxPrice: 105000,
    avgPrice: 89000,
    suggestedBuyPrice: 62000,
    suggestedSalePrice: 78000,
    suggestedShop1Price: 95000,
    suggestedShop2Price: 78000,
    suggestedShop3Price: 70000,
    activeSellersCount: 35,
    totalSellersCount: 58,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۵٪ آنلاین، سود ۵۳٪ حضوری', competitiveEdge: 'تضمین اصالت بارکد ژاپن', targetAudience: 'خوش‌نویسان، طراحان و دانشجویان', inventoryAdvice: 'تامین رنگ‌های پرطرفدار (آبی تیره، مشکی، سبز کله‌غازی)' },
  },
  {
    torobCode: 'TRB-ART-FABER-24',
    title: 'مداد رنگی ۲۴ رنگ فابر کاستل مدل کلاسیک جعبه مقوایی',
    category: 'ابزار نقاشی و هنر',
    subCategory: 'مداد رنگی',
    brand: 'Faber-Castell',
    unit: 'بسته',
    image: STATIONERY_IMAGE_BANK.coloredPencilsFaber,
    torobUrl: 'https://torob.com/search/?query=%D9%85%D8%AF%D8%A7%D8%AF+%D8%B1%D9%86%DA%AF%DB%8C+%D9%81%D8%A7%D8%A8%D8%B1+%DA%A9%D8%A7%D8%B3%D8%AA%D9%84+24+%D8%B1%D9%86%DA%AF',
    specs: { 'تعداد رنگ': '۲۴ رنگ درخشان', 'فرم بدنه': 'شش‌ضلعی ارگونومیک کلاسیک', 'فناوری مغزی': 'SV ضدشکستگی در برابر ضربه', 'پایه‌رنگ': 'روغنی نرم با پوشش‌دهی فوق‌العاده' },
    description: 'استاندارد جهانی مداد رنگی دانش‌آموزی و هنری با ترکیب‌پذیری بی‌نظیر رنگ‌ها و نوک مقاوم.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.9, price: 395000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ضمانت اصالت آلمان', shopUrl: 'https://www.digikala.com' },
      { storeName: 'هنرآموز (ترب)', city: 'تهران', score: 4.8, price: 345000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال ایمن', shopUrl: 'https://torob.com' },
    ],
    minPrice: 345000,
    maxPrice: 430000,
    avgPrice: 382000,
    suggestedBuyPrice: 285000,
    suggestedSalePrice: 342000,
    suggestedShop1Price: 410000,
    suggestedShop2Price: 342000,
    suggestedShop3Price: 310000,
    activeSellersCount: 28,
    totalSellersCount: 48,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۰٪ آنلاین، سود ۴۳٪ حضوری', competitiveEdge: 'ارسال با دفتر نقاشی سیمی خطی‌نو', targetAudience: 'دانش‌آموزان، هنرجویان نقاشی و والدین', inventoryAdvice: 'افزایش ذخیره قبل از مهر و عید نوروز' },
  },
  {
    torobCode: 'TRB-HL-STABILO-BOSS',
    title: 'ماژیک علامت‌گذار استابیلو مدل Boss Original ست ۴ رنگ',
    category: 'نوشت‌افزار و تحریر',
    subCategory: 'ماژیک و هایلایتر',
    brand: 'Stabilo',
    unit: 'بسته',
    image: STATIONERY_IMAGE_BANK.highlighterStabilo,
    torobUrl: 'https://torob.com/search/?query=%D9%87%D8%A7%DB%8C%D9%84%D8%A7%DB%8C%D8%AA%D8%B1+%D8%A7%D8%B3%D8%AA%D8%A7%D8%A8%DB%8C%D9%84%D9%88+%D8%A8%D8%A7%D8%B3',
    specs: { 'فناوری ضدخشک‌شدن': 'تا ۴ ساعت بدون درب Anti-Dry-Out', 'رنگ‌های ست': 'زرد، صورتی، سبز، نارنجی فسفری', 'ضخامت خط': '۲ تا ۵ میلی‌متر (تخت و نوک‌تیز)', 'کشور سازنده': 'آلمان' },
    description: 'اصلی‌ترین هایلایتر جهان با درخشش فوق‌العاده روی متن‌های چاپی و دست‌نویس.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.9, price: 285000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'اصالت کالا', shopUrl: 'https://www.digikala.com' },
      { storeName: 'استابیلو سنتر (ترب)', city: 'تهران', score: 4.8, price: 255000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال اکسپرس', shopUrl: 'https://torob.com' },
    ],
    minPrice: 255000,
    maxPrice: 310000,
    avgPrice: 279000,
    suggestedBuyPrice: 205000,
    suggestedSalePrice: 252000,
    suggestedShop1Price: 295000,
    suggestedShop2Price: 252000,
    suggestedShop3Price: 228000,
    activeSellersCount: 22,
    totalSellersCount: 39,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۳٪ آنلاین، سود ۴۴٪ حضوری', competitiveEdge: 'تضمین ماندگاری جوهر', targetAudience: 'کنکوری‌ها، وکلا، پزشکان و دانشجویان', inventoryAdvice: 'تامین مستمر' },
  },
  {
    torobCode: 'TRB-OFF-STAPLER-MAX',
    title: 'دستگاه منگنه مکس مدل HD-50 ژاپن اورجینال فلزی',
    category: 'لوازم اداری و بایگانی',
    subCategory: 'منگنه و پانچ',
    brand: 'MAX',
    unit: 'عدد',
    image: STATIONERY_IMAGE_BANK.binderPapcoOffice,
    torobUrl: 'https://torob.com/search/?query=%D9%85%D9%86%DA%AF%D9%86%D9%87+%D9%85%DA%A9%D8%B3+hd50',
    specs: { 'ظرفیت دوخت': 'تا ۳۰ برگ کاغذ ۸۰ گرم', 'سایز سوزن': '24/6 و 26/6', 'بدنه': 'تمام فولادی آبکاری شده با روکش پلاستیک مقاوم', 'مکانیزم': 'لودر آسان سوزن' },
    description: 'بادوام‌ترین ماشین دوخت اداری جهان با طول عمر بالای ۱۰ سال بدون گیر کردن سوزن.',
    sellers: [
      { storeName: 'دیجی‌کالا', city: 'تهران', score: 4.8, price: 340000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'گارانتی اصالت', shopUrl: 'https://www.digikala.com' },
      { storeName: 'اداری کالا (ترب)', city: 'تهران', score: 4.9, price: 298000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'تحویل اکسپرس', shopUrl: 'https://torob.com' },
    ],
    minPrice: 298000,
    maxPrice: 360000,
    avgPrice: 325000,
    suggestedBuyPrice: 240000,
    suggestedSalePrice: 295000,
    suggestedShop1Price: 345000,
    suggestedShop2Price: 295000,
    suggestedShop3Price: 268000,
    activeSellersCount: 19,
    totalSellersCount: 32,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۲۳٪ آنلاین، کالای ماندگار', competitiveEdge: 'ارسال با یک بسته سوزن منگنه هدیه', targetAudience: 'شرکت‌ها، بانک‌ها و ادارات', inventoryAdvice: 'تامین ۲۰ عدد در انبار' },
  },
  {
    torobCode: 'TRB-OFF-CALC-CASIO-991',
    title: 'ماشین حساب مهندسی کاسیو مدل fx-991EX ClassWiz اورجینال',
    category: 'لوازم اداری و بایگانی',
    subCategory: 'ماشین‌حساب',
    brand: 'Casio',
    unit: 'دستگاه',
    image: STATIONERY_IMAGE_BANK.officeGeneral,
    torobUrl: 'https://torob.com/search/?query=%D9%85%D8%A7%D8%B4%DB%8C%D9%86+%D8%AD%D8%B3%D8%A7%D8%A8+%DA%A9%D8%A7%D8%B3%DB%8C%D9%88+991ex',
    specs: { 'تعداد توابع': '۵۵۲ تابع پیشرفته', 'نمایشگر': 'طبیعی با ووضوح بالا Natural V.P.A.M', 'منبع تغذیه': 'دوگانه (نور خورشید و باتری)', 'اصالت': 'گارانتی پوزیترون' },
    description: 'محبوب‌ترین ماشین‌حساب مهندسی دانشگاهی با قابلیت محاسبه ماتریس، انتگرال، معادلات چندمجهولی و آمار.',
    sellers: [
      { storeName: 'دیجی‌کالا (با گارانتی اصلی)', city: 'تهران', score: 4.9, price: 1950000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'گارانتی پوزیترون', shopUrl: 'https://www.digikala.com' },
      { storeName: 'کاسیو سنتر ایران (ترب)', city: 'تهران', score: 4.9, price: 1780000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ضمانت اصالت ژاپن', shopUrl: 'https://torob.com' },
      { storeName: 'تایم تحریر', city: 'مشهد', score: 4.7, price: 1820000, inStock: true, lastUpdated: 'پایگاه داده مرجع', updatedRecently: false, warranty: 'ارسال رایگان', shopUrl: 'https://timetahrire.com' },
    ],
    minPrice: 1780000,
    maxPrice: 2150000,
    avgPrice: 1890000,
    suggestedBuyPrice: 1550000,
    suggestedSalePrice: 1770000,
    suggestedShop1Price: 1950000,
    suggestedShop2Price: 1770000,
    suggestedShop3Price: 1650000,
    activeSellersCount: 14,
    totalSellersCount: 30,
    lastUpdated: 'داده مرجع بازار (کاتالوگ بنچمارک)',
    isLiveScraped: false,
    isBenchmarkCatalog: true,
    isGenericStockPhoto: true,
    sourceLink: 'https://torob.com/price-list/110/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1-stationery-lavazem-tahrir-%D9%84%DB%8C%D8%B3%D8%AA-%D9%82%DB%8C%D9%85%D8%AA/',
    aiRecommendation: { marginStrategy: 'سود ۱۴٪، کالای با ارزش ریالی بالا و تقاضای قطعی دانشجویان مهندسی', competitiveEdge: 'تضمین اصالت کد QR کاسیو', targetAudience: 'دانشجویان فنی، اساتید و مهندسان', inventoryAdvice: 'تامین مستمر' },
  },
];
